from pathlib import Path

BASE = Path(__file__).resolve().parent

REPO_STRUCTURE = {
    "README.md": """# Global Algorithmic Governance Institute — Website Scaffold

Status: PROPOSED / INITIAL

This package creates a static public-facing site scaffold for the Global Algorithmic Governance Institute research program.

The website layer does not establish government recognition, regulatory authority, certification authority, legal status, or an adopted international standard.

## Structure

- index.html
- styles.css
- docs/links.md
- docs/business-profile.md
- docs/methodology.md
- docs/research.md

## Status discipline

BUILT · SPECIFIED · PROTOTYPED · TESTED · VERIFIED · PLANNED · HYPOTHETICAL
""",
    "index.html": "<!-- Generated by setup_github_repo.py; see repository index.html -->",
    "styles.css": "/* Generated by setup_github_repo.py; see repository styles.css */",
    "docs/links.md": "<!-- Generated registry placeholder -->",
    "docs/business-profile.md": "<!-- Generated profile schema placeholder -->",
    "docs/methodology.md": "<!-- Generated methodology placeholder -->",
    "docs/research.md": "<!-- Generated research notes placeholder -->",
}

def initialize_repository() -> None:
    print("Starting repository initialization...")
    for relative_path, content in REPO_STRUCTURE.items():
        target = BASE / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content.strip() + "\n", encoding="utf-8")
        print(f"created: {relative_path}")
    print("Initialization complete.")

if __name__ == "__main__":
    initialize_repository()
